### PR TITLE
Style Updates

### PR DESCRIPTION
**Pull request by potatoqualitee**
@LaurentDardenne

Thanks again for the updates! This is a ton of work and I appreciate it.

I've updated the style to [OTBS](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS)) which also allowed me to better understand what the module is doing. I'm unsure about the workflows, however. Can you please let me know how I can ensure all required tests run when I `push` to the repo?

Also, can you tell me more about these two variables and one parameter?

```
AMParameters
sbIsUpdatable
F
```

### CODE REVIEW

**Comment by LaurentDardenne** [comment]
About OTBS, I don't use this format because when I'm looking for a missing curly braces the alignment helps to find it.
I will wait for your commit because I have to deliver the last modifications.

For **$AMParameters**, it is a temporary variable containing the parameters of Add-Member, in the function I reuse the name with different contents.
The parameters of the Action 'ModulesParameter' and 'PrereleaseModulesParameter' being identical, the same rule analysis is applied.

**$sbIsUpdatable** bundles tests for easy proofreading
```powershell
 if ($Action.CacheType -eq 'Immutable' -and $Action.isCacheUpdatable )
```
instead of duplicating:
```powershell
 if ($Action.CacheType -eq 'Immutable' -and ( ($Action.ModulesParameter -match '::') -or ($Action.PrereleaseModulesParameter -match '::')))
 ```
 >> one parameter?

Which one ?

>>Can you please let me know how I can ensure all required tests run when I push to the repo?

I only used the '_workflow_dispatch:_' event.
You need to create a personal access token for Github Cli. This PAT is used by the '**RunWorkFlows.yml**' and '**CleanWorkFlowsHistory.yml**' workflows.
I haven't coded checks for these prerequisites, maybe later.

In the next delivery it is no longer necessary to change the repository name in the code of 'RunWorkFlows.yml' and 'CleanWorkFlowsHistory.yml'.

There remains the case of Pester which requires an infra (docker or external), you need at least one account and a cloudsmith repository linked to your repository.
But we can't share secrets in case of fork, so we have to document this case.

You can already run the 'MatrixCacheDemo.yml' workflow, it contains a dependency on my test repository _https://www.myget.org/F/ottomatt_.
This one is persistent.

**Comment by potatoqualitee** [comment]
Thank you! is the `sb` in `sbIsUpdatable` short for the phrase "software bundle"? i am looking to make a few more variable names more descriptive at first glance.

the parameter is "-F" 

```
Add-FunctionnalError -Message ($PSModuleCacheResources.ModuleCannotContainPrerelease -F $version)
```

Since the repo is wholly contained and doesn't interact with other github repos, I think the GITHUB_TOKEN is good enough and won't require a PAT.

So if I change every workflow_dispatch to workflow_dispatch and push, we should be set?

**Comment by LaurentDardenne** [comment]
_>>is the sb in sbIsUpdatable short for the phrase "software bundle"?_ 
No, it's one of my conventions for ScriptBlock :-) . I could have used the term Delegate but it's more C# oriented.

_>>i am looking to make a few more variable names more descriptive at first glance._
I made sure to name them explicitly except for this type of name: $MCI for ModuleCacheInformation.
But I could be wrong.

_>>the parameter is "-F"_
It is a Powershell operator that encapsulates the _Object.ToString()_ method.
Resource file strings may contain 'substitutions', example "Error 1 variable name '{0}'"

_>>I think the GITHUB_TOKEN is good enough_ 
I tested this token but it is not suitable as it is. We must add rights to use Github CLi in a workflow.
Either you add a PAT or you remove these workflows (WKF), as I configured all the WKFs in manual trigger I just added these 2 WKFs to run them all in one call.
As I often committed during the dev on a master branch I didn't want to trigger something that failed.

To check the creation of the cache we have two passes, the first of creation ('CleanWorkFlowsHistory.yml') and the second of restoration 'RunWorkFlows.yml'. The cleaning of cache files before testing is our responsibility.

_>>So if I change every workflow_dispatch to workflow_dispatch and push, we should be set?_
You mean "workflow_dispatch to push" ?

You can already run _Pester.yml_ and _MatrixCacheDemo.yml_ by **[push**].
Maybe it is necessary to reduce the number of WKF, Pester covers the code but not the execution of workflows.
As there are now many possible scenarios, I haven't yet figured out how to deal with this topic more effectively.

**Comment by LaurentDardenne** [comment]
I can create a pull request for the latest changes, am I waiting for this pull request to merge?

**Comment by potatoqualitee** [comment]
Yeah sorry, I'll merge now.

**Comment by LaurentDardenne** [comment]
Merci :-)

**Pull request merged**
