### PR TITLE
Allow action to run inside a container job

### LINKED ISSUE #43: Action fails when used with a container job
Given the following workflow:

```yaml
name: Cache Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/powershell:ubuntu-22.04
    steps:

      - uses: actions/checkout@v3

      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v5.2
        with:
          modules-to-cache: Az.Network
```

The action fails:
image

Here's the full output from the action:

```text
Run potatoqualitee/psmodulecache@v5.2
  with:
    modules-to-cache: Az.Network
    shell: pwsh
    updatable: false
    prefixidentifier: false
Run Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1
  Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1
  Write-Output "Getting variables for cacher"
  
  $Parameters = @{
    Modules = "Az.Network"
    PrereleaseModules = ""
    Shells = "pwsh"
    Updatable = [boolean]::Parse("false")
    PrefixIdentifier = [boolean]::Parse("false")
  }
  Write-Output "Action Parameters = $([PsCustomObject]$Parameters)"
  
  $ActionParameters = New-ModuleCacheParameter @Parameters
  
  $ModuleCaches = Get-ModuleCache $ActionParameters
  "keygen=$($ModuleCaches.Key)" >> $env:GITHUB_OUTPUT
  
  $Paths = @(New-ModuleSavePath $ModuleCaches.ModuleCacheInformations)
  
  # Accommodate multi-line
  "modulepath<<EOF" >> $env:GITHUB_OUTPUT
  $Paths >> $env:GITHUB_OUTPUT
  "EOF" >> $env:GITHUB_OUTPUT
  
  $null = $ModuleCaches | Export-CliXml -Path (Join-Path $home -ChildPath $CacheFileName)
  shell: pwsh -command ". '{0}'"
  
Import-Module: /__w/_temp/393f6afa-82ee-45c2-8362-0fdf70641abd.ps1:2
Line |
   2 |  Import-Module /home/runner/work/_actions/potatoqualitee/psmodulecache …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module
     | '/home/runner/work/_actions/potatoqualitee/psmodulecache/v5.2/PSModuleCache.psd1' was not loaded because no valid module file was found in any module directory.
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by flcdrg**
Fixes #43

### CODE REVIEW

**Comment by LaurentDardenne** [comment]
hi,

[This test ](https://github.com/potatoqualitee/psmodulecache/blob/1c1b8c44dbaa6503295eba914cc95701beb8c81f/PSModuleCache.psm1#L467)should perhaps trigger an exception if the 'SUDO' command does not exist, otherwise a necessary step is not performed for OS other than Windows. User code using this action would later fail.

**Comment by flcdrg** [comment]
The problem is that you're not guaranteed to find 'sudo' available if you're using a container job. I'll do some more testing

**Comment by flcdrg** [comment]
I've expanded the test workflow to confirm that a cached module works as expected. I've also added a warning if 'sudo' is not found.

**Comment by LaurentDardenne** [comment]
I think that using a warning instead of an exception is not appropriate in this context.

If the _SUDO_ operation is necessary but the command does not exist, we must stop the caching processing, because to correct this problem we must install this command in the targeted container (if I understood correctly). The current error message does not indicate this additional installation.

Test :
image

Then the current Pester tests pass, which is normal since they test the code of the module and not its dependencies/prerequisites which, to this day, are supposed to still exist.

[Test](https://github.com/LaurentDardenne/psmodulecache/actions/runs/3816396379) :  
image

Used [code](https://github.com/LaurentDardenne/psmodulecache/blob/Test_missing_step_SUDO/PSModuleCache.psm1#L466)

**Comment by flcdrg** [comment]
Hmm.. ok, so maybe we need to test if the sudo operation is required, and fail if it is required but can't be run.

I think it really depends on the container image as to how the directories have been set up. Adding sudo would require creating a custom image, which most users would not want to bother with.

**Comment by flcdrg** [comment]
Updated PR to pass through whether we're inside a container job or not. Existing functionality is preserved if we're not inside a container job.

An alternate approach would be to set an environment var on the composite action steps and then just test the value of that variable within `Get-ModuleSavePath`

**Comment by potatoqualitee** [comment]
Thanks everyone! I was in Paris 🥖 last week and am just getting to this, is main good enough or does it need a release?

**Comment by potatoqualitee** [comment]
LGTM! Thank you 🙇🏼

**Pull request merged**
