### PR TITLE
vNext5.0

### PR DESCRIPTION
**Pull request by LaurentDardenne**
Add features (updatable module, multiple repositories) and fix bugs.

Todo : 

Change name of repo into 'RunWorkFlows.yml' et 'CleanWorkFlowsHistory.yml'

Create a personal access token for Github Cli.
Create a tag 5.0

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Thank you so much, @LaurentDardenne ! I'll take a look ASAP.

Are users required to create a PAT or just me as the repo owner?

**Comment by LaurentDardenne** [comment]
For the PAT, the repo owner.  see [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)

Note : 
- All actions are configured with "_workflow_dispatch_".
- I'm not sure of my translations into 'Readme.md' file.

**Comment by LaurentDardenne** [comment]
About "_Change name of repo into 'RunWorkFlows.yml' et 'CleanWorkFlowsHistory.yml'_"

For Github CLI instead of:
```powershell
$Repo='PSLDA/psmodulecache'
```
you can use this directly:
```powershell
$Repo=$env:GITHUB_REPOSITORY
```
This will limit the necessary modifications in the event of a fork.

**Comment by adilio** [comment]
This is looking pretty great so far, @LaurentDardenne!

Pardon my confusion, I see that the ability to configure additional public repositories is present. Is there a plan to support private repositories that require a credential (as per #22), or is that already there and I'm missing the code?

**Comment by potatoqualitee** [comment]
@LaurentDardenne -- I'm slammed right now and have asked @adilio to do a code review as he wanted some of the features you implemented 🥳

**Comment by LaurentDardenne** [comment]
_>>Is there a plan to support private repositories that require a credential_

I haven't implemented this part. I need to find a solution to create a test repository.
It would be better to have a test repository linked to this repository. For module duplication tests I tried locally but there is a [bug](https://github.com/PowerShell/PowerShellGetv2/issues/491#issuecomment-1208033467)
The steps being on several Powershell instances, this case must be studied. See also [credential management ](https://github.com/PowerShell/PowerShellGet/issues/64).

**Comment by LaurentDardenne** [comment]
My free subscription to Myget does not allow creating a private repository requiring credentials.

**Comment by potatoqualitee** [comment]
Sweet, Dave Carroll sent me this on twitter -- https://hub.docker.com/r/sunside/simple-nuget-server/

allows you to do a credentialed login

**Comment by adilio** [comment]
As well, just for testing, you can setup a Core plan on Cloudsmith.com for a free private repo. Full-disclosure, I work for them, but IMO it's the easiest way to setup a test repo without having to setup any servers or containers.

**Comment by LaurentDardenne** [comment]
_>>you can setup a Core plan on Cloudsmith.com for a free private repo_
I will look at this.

I don't know Docker, although that's an opportunity to learn. Originally I wanted to migrate my repositories from Appveyor to Github Action.

What I suggest is to release this version if you like it and add the missing requested functionality in another version.

**Comment by LaurentDardenne** [comment]
Before correcting the code I will test with another provider to confirm certain cases and complete the documentation.

Adding pester tests for repositories seems a bit difficult to share, since they depend on an infrastructure external to github.
In this case the use of a Nuget server in Docker is more appropriate but requires, it seems to me, implementation documentation for those who would like to fork this repository.

**Comment by adilio** [comment]
Heya Laurent, thanks for all your work on this, and apologies for my radio silence (lots of "Life" things going on currently).

I'm in agreement with you that we can leave off the private repository with credential bit to another version/PR.

I'll just make some suggestions for the README and approve shortly.

Thanks again for all your work!

**Comment by adilio** [comment]
OK, strike that, LGTM! I say ship it! 🚀
(I don't have reviewer perms, but we can always fix typo's in a separate PR)

**Comment by potatoqualitee** [comment]
Thank you both! 💯  i will merge, make a few adjustments then publish

**Comment by LaurentDardenne** [comment]
For information :
The market place uses the latest version of the _Readme.md_ file although the Action version has not been updated. The '_Use latest version_' button always points to the latest version.
https://github.com/marketplace/actions/powershell-module-cache

**Comment by potatoqualitee** [comment]
oh no! doh, i forgot about that. ill fix it tomorrow

**Comment by potatoqualitee** [comment]
and ill put back the old readme now

**Pull request merged**
