### PR TITLE
Test Changes

### PR DESCRIPTION
**Pull request by potatoqualitee**
This run looks nice -- is it the output you expected, @LaurentDardenne?

https://github.com/potatoqualitee/psmodulecache/runs/8246200070?check_suite_focus=true

### CODE REVIEW

**Comment by potatoqualitee** [comment]
sweet, 8 passes. i havent yet dug into the tests -- are the old version tests still included?

**Comment by potatoqualitee** [comment]
The Previous tests included tests for old implementations as a reassurance that the expected behavior continues even in older versions. I've added them back and we'll see if it works 🤞🏼

**Comment by potatoqualitee** [comment]
Nice, it does 👍🏼  I'll likely do a new release within the next few hours.

**Comment by potatoqualitee** [comment]
thanks for the note about restarting the workflows. hopefully powershellget 3 fixes this 😞

**Comment by LaurentDardenne** [comment]
_>>The Previous tests included tests for old implementations as a reassurance that the expected behavior continues even in older versions._
I thought the action code was linked to the version of the repository (Tag) as shown [here](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace).
In this case the old versions continue to work.

_>>hopefully powershellget 3 fixes this_
I will try to find out the cause, but locally I never had this problem.
For PSGet3 I don't know how MS will manage the runner update, in my opinion it's a bit early to worry about it.

**Comment by potatoqualitee** [comment]
> I thought the action code was linked to the version of the repository (Tag) as shown here

If I create a workflow that accidentally deletes all of my releases, then my previous versions will no longer work and I will be alerted to it. I do not see a reason to delete tests in general unless they are problematic.

> I will try to find out the cause, but locally I never had this problem.

PS Get is flaky as are runners, unfortunately. Combine the two and some weird stuff can surface.

**Pull request merged**
