### PR TITLE
V next5.0 with credential

### PR DESCRIPTION
**Pull request by LaurentDardenne**
Add Feature : use repositories with credential

I removed many useless actions that I replaced by matrices and Pester tests.
The readme is up to date.

Following your last style modifications, the modifications were too important for me to correct line by line.
I'm sorry to overwrite what you did :-/

We can cancel this PR, you tell me what tools you use so that I reformat the code (PSSA?) specifying which rules to apply.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
thank you! can you please have some tests run on `push` like they did before? i'd like the same coverage if possible.

**Comment by LaurentDardenne** [comment]
Yes, I'll reformat the code like you did, I'm trying to do that this week.

**Comment by LaurentDardenne** [comment]
I reformatted the module code and changed some variable names ($MCI,$MCP)

On the 'cloudsmith' website, create an organisation nammed 'actionpsmodulecache',
next create a repository Nuget nammed 'privatepsmodulecache'.

To use other names, modify the content of the following variables in the files:
```powershell
  $CloudsmithRepositoryName='privatepsmodulecache'
  $CloudsmithUriLocation='https://nuget.cloudsmith.io/actionpsmodulecache/privatepsmodulecache/v2/'
```

I only configured the Pester Action in push, because for the moment we do not know the end or the order of execution in order to chain the following ones.
Maybe this can help order the actions:
https://github.com/marketplace/actions/workflow-dispatch-and-wait

**Comment by potatoqualitee** [comment]
There are no run jobs under Actions :/

**Comment by LaurentDardenne** [comment]
_>>There are no run jobs under Actions :/_
Can you clarify, I don't see what the problem is.

**Comment by potatoqualitee** [comment]
Yes, I would like all changes to be tested like they used to be. You have created some workflows that should be triggered on push but I am not seeing any runs here:

https://github.com/potatoqualitee/psmodulecache/actions

**Comment by potatoqualitee** [comment]
Sorry, I wasn't referring to your previous PR. Prior to your first PR, every commit to this repo tested a number of things. You can see the result of these tests at https://github.com/potatoqualitee/psmodulecache/actions

I will change the push for main  to a push for all and we can go from there.

**Comment by potatoqualitee** [comment]
I just checked and the Pester test is not set to main. It just says push yet the Actions are not running.

I am eager to get this merged and do a release but I'm knee deep in a number of other projects and if fixing the tests is up to me, it'll be a while. I'm looking for tests to run like they used to so that I can be confident that future changes do not negatively impact the expected functionality.

**Comment by potatoqualitee** [comment]
Do you know why your VS Code re-reformatted the tests? Can you put it back please? Also, can you Skip the cloudsmith tests for now?

**Comment by potatoqualitee** [comment]
VSCode has a .vscode folder with the specified formatting style. It should have acknowledged that and just made the changes for you. I re-read your initial comment and will see what I can do.

**Comment by potatoqualitee** [comment]
yeah, i'd have to reformat it all over again which previously took me a while. I'd like to close this PR until the reformatting issue is resolved. I'll create a new branch that changes the pester test to push and pull_request. Désolé.

**Comment by LaurentDardenne** [comment]
_>>Do you know why your VS Code reformatted the tests?_
The problemb is that I continued the evolutions on my original code, I did not report the modifications that you had made in the meantime.

_>>Can you put it back please?_
I'm a bit lost there, I prefer to leave it as it is so as not to confuse everything.

_>>Also, can you Skip the cloudsmith tests for now?_
The best is to place a return at the beginning of the file './test/GHA.PSmoduleCache.TestRepositoriesCredential.Tests.ps1'
Or modify the Pester tags in the './test/Run.ps1' file.

**Comment by potatoqualitee** [comment]
> The problemb is that I continued the evolutions on my original code

Ahh, are you able to get the newest commits now? I use GitHub Desktop to simplify my workflow, you may find it useful as well.

> I'm a bit lost there, I prefer to leave it as it is so as not to confuse everything.

Unfortunately, we are at an impasse as I also do not want to undo my work.

> The best is to place a return at the beginning of the file './test/GHA.PSmoduleCache.TestRepositoriesCredential.Tests.ps1'

Since this PR has been closed, this problem no longer exists. If, in the future, I have time to parse apart the actual changes in the code, I'll see if I can add back support for private repos.

**Comment by LaurentDardenne** [comment]
>>I'll see if I can add back support for private repos.

I can redo the PR starting from a version that suits you, we just have to coordinate and avoid cross-commits.

In the meantime, in the module it is necessary to correct this:
```powershell
    Set-PSRepository PSGallery -InstallationPolicy Trusted
```
In :
```powershell
  try {
        Get-PSRepository PSGallery -EA Stop > $null
        Set-PSRepository PSGallery -InstallationPolicy Trusted
  catch {
        if ($_.CategoryInfo.Category -ne 'ObjectNotFound')
        { throw $_ }
   }
```
Because we may want to use only private repositories and disable PSGallery.

**Comment by potatoqualitee** [comment]
Sounds good, I am not making any changes.

**Pull request closed without merging**
