### PR TITLE
Fix for issue 48 - Case sensitivity of the module name running under Linux OS

### PR DESCRIPTION
**Pull request by Callidus2000**
Uses the information from Find-Module to correct the module name which is used further on. Find-Module does not care about the input case but returns the official case.

### CODE REVIEW

**Comment by Callidus2000** [comment]
Oh, forgotten:

Just as an idea for a possible approach to the problem of dependencies: Take the parameters from the action input as Search-Criteria for `Find-Module` and add the `-IncludeDependencies` parameter. As a result you get a list of all needed modules, names with the right case etc.. Then take this data for further processing of the modules (install/save/cache etc.) instead of the original inputs.

**Comment by LaurentDardenne** [comment]
>>You've extracted it into another function, I've used the already initiated objects for gaining the same info.

It is preferable, in my opinion, to centralize the modification during the first pass and to modify the name [directly in the serialized](https://github.com/LaurentDardenne/psmodulecache/commit/509e6c30b8d3d8e593652cda6e0b907e50f2d0bd#diff-75ed9b7c3f8092a73fe27c9c4357c609d99104c33504f58eaca1902cf94b8d84R506) file used in the second pass by the Save-ModuleCache function.

>>As a result you get a list of all needed modules, names with the right case etc..

Yes that's what I implemented, it remains to test [different use cases](https://github.com/LaurentDardenne/psmodulecache/tree/FeatureModuleDependencies/test/Dependencies/Gallery).

**Comment by LaurentDardenne** [comment]
Hello, I think you can close this PR, the modifications to fix this bug must also manage dependent modules ([Example](https://github.com/LaurentDardenne/psmodulecache/blob/FeatureModuleDependencies/test/Dependencies/Gallery/String/3.0.0/String.psd1#L54 )).

**Comment by Callidus2000** [comment]
Closed as I understand your concerns.
The point with two repositories may be a little bit academic as I would not expect this to happen in real life.
Thanks for looking into it.

**Comment by LaurentDardenne** [comment]
>>The point with two repositories may be a little bit academic as I would not expect this to happen in real life.

I agree. A priori the projects using this action mostly use PSGallery.

Note:
In a module specification the identity, and uniqueness, of a module is based on (Name,Version,GUID).
In a Nuget repository the GUID is not used because the identity, and uniqueness, is based on the name and version (which make up its ID).
We can therefore have 2 modules of the same name with a different GUID, but they must be in two repositories and be installed in separate directories (psmodulepath).

An object returned by Find-Module does not contain the module GUID, but the name of the repository in which it was found.
In this context we therefore have an ID based on (Name,Version,RepositoryName)

In a way, as I understand it, the GUID serves as a local repository selector. Moreover, Install-Module does not allow to specify a path, but Save-Module proposes it...

**Comment by LaurentDardenne** [comment]
Hi,
_>>the modifications to fix this bug must also manage dependent modules_

This is implemented in version 6.0.
Sorry for the wait.

**Pull request closed without merging**
